import * as React from "react";
import Grid from "@mui/material/Grid";
import {
  Box,
  Paper,
  Typography,
  Button,
  TextField,
  MenuItem,
  Chip,
  Divider,
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  Alert,
  Switch,
  FormControlLabel,
  useMediaQuery,
  useTheme,
} from "@mui/material";
import { DataGrid } from "@mui/x-data-grid";
import BusinessOutlinedIcon from "@mui/icons-material/BusinessOutlined";
import ReportProblemOutlinedIcon from "@mui/icons-material/ReportProblemOutlined";

import {
  listTenants,
  getTenantById,
  updateTenant,
  deleteTenant,
  listTenantMembers,
  createTenantMember,
  updateTenantMember,
  deleteTenantMember,
} from "../api/tenants";
import { useCachedFetch } from "../hooks/useCachedFetch";
import { listFrom } from "../api/shape";
import { useAuthContext } from "../auth/AuthContext";

import { BRAND, DATAGRID_SX } from "../theme/brand";
import PageHeader from "../components/common/PageHeader";
import BrandSnackbar from "../components/common/BrandSnackbar";
import SectionPaper from "../components/common/SectionPaper";
import { formatDate } from "../utils/format";

// Fase 2 — SummaryCard aligned with the Tokens page version. Same
// shell tokens; `accent` is the semantic color of the big number.
function SummaryCard({ title, value, accent = BRAND.teal }) {
  return (
    <Paper
      elevation={0}
      sx={{
        p: 2,
        height: "100%",
        minHeight: 96,
        borderRadius: 2,
        border: `1px solid ${BRAND.border}`,
        display: "flex",
        flexDirection: "column",
        justifyContent: "space-between",
      }}
    >
      <Typography sx={{ fontSize: 13, color: "text.secondary", fontWeight: 600 }}>
        {title}
      </Typography>

      <Typography
        sx={{
          fontSize: 28,
          fontWeight: 800,
          color: accent,
          lineHeight: 1.1,
          mt: 1,
        }}
      >
        {value}
      </Typography>
    </Paper>
  );
}

// Role & status chips — colors now come from BRAND tokens.
// ADMIN uses the neutral teal (it's a privileged-but-not-superuser
// role), USER the subtle dark soft, Active/Inactive the role
// success/error pair.
function renderRoleChip(role) {
  const value = String(role || "").toUpperCase();

  if (value === "OWNER") {
    return <Chip label="OWNER" size="small" sx={{ fontWeight: 700 }} />;
  }

  if (value === "ADMIN") {
    return (
      <Chip
        label="ADMIN"
        size="small"
        sx={{
          bgcolor: BRAND.tealSoft,
          color: BRAND.tealText,
          fontWeight: 700,
        }}
      />
    );
  }

  if (value === "USER") {
    return (
      <Chip
        label="USER"
        size="small"
        sx={{
          bgcolor: BRAND.darkSoft,
          color: BRAND.dark,
          fontWeight: 700,
        }}
      />
    );
  }

  return <Chip label={value || "UNKNOWN"} size="small" />;
}

function renderActiveChip(isActive) {
  return isActive ? (
    <Chip
      label="Active"
      size="small"
      sx={{
        bgcolor: BRAND.alert.successSoft,
        color: BRAND.alert.success,
        fontWeight: 700,
      }}
    />
  ) : (
    <Chip
      label="Inactive"
      size="small"
      sx={{
        bgcolor: BRAND.alert.errorSoft,
        color: BRAND.alert.error,
        fontWeight: 700,
      }}
    />
  );
}


function TenantDialog({
  open,
  tenant,
  submitting,
  onClose,
  onSubmit,
}) {
  const [name, setName] = React.useState("");
  const [externalIdpTenant, setExternalIdpTenant] = React.useState("");
  const [maxDevices, setMaxDevices] = React.useState("");
  const [tenantDb, setTenantDb] = React.useState("");
  const [idpApiToken, setIdpApiToken] = React.useState("");

  React.useEffect(() => {
    if (open) {
      setName(tenant?.name || "");
      setExternalIdpTenant(tenant?.externalIdpTenant || "");
      setMaxDevices(tenant?.maxDevices ?? "");
      setTenantDb(tenant?.tenantDb || "Auto-generated by backend");
      // Write-only field — the stored token is never sent back down, so
      // this always starts blank regardless of whether one is configured.
      setIdpApiToken("");
    } else {
      setName("");
      setExternalIdpTenant("");
      setMaxDevices("");
      setTenantDb("");
      setIdpApiToken("");
    }
  }, [open, tenant]);

  const handleSubmit = () => {
    const payload = {
      name: String(name || "").trim(),
      externalIdpTenant: String(externalIdpTenant || "").trim(),
      maxDevices: Number(maxDevices),
    };

    // Only sent when the admin actually typed something, so leaving it
    // blank never clobbers an already-configured token.
    if (String(idpApiToken || "").trim()) {
      payload.idpApiToken = String(idpApiToken).trim();
    }

    onSubmit?.(payload);
  };

  const isDisabled =
    !String(name || "").trim() ||
    !String(externalIdpTenant || "").trim() ||
    String(maxDevices || "").trim() === "";

  return (
    <Dialog open={open} onClose={onClose} fullWidth maxWidth="sm">
      <DialogTitle>Edit Tenant</DialogTitle>

      <DialogContent>
        <Box sx={{ display: "grid", gap: 2, pt: 1 }}>
          <TextField
            label="Tenant Name"
            value={name}
            onChange={(e) => setName(e.target.value)}
            fullWidth
            required
          />

          <TextField
            label="Ext IdP Tenant"
            value={externalIdpTenant}
            onChange={(e) => setExternalIdpTenant(e.target.value)}
            fullWidth
            disabled
          />

          <TextField
            label="Tenant DB"
            value={tenantDb}
            fullWidth
            disabled
          />

          <TextField
            label="Max Devices"
            type="number"
            value={maxDevices}
            onChange={(e) => setMaxDevices(e.target.value)}
            fullWidth
            required
          />

          <TextField
            label="IDP API Token"
            type="password"
            value={idpApiToken}
            onChange={(e) => setIdpApiToken(e.target.value)}
            fullWidth
            placeholder={
              tenant?.hasIdpApiToken
                ? "•••••••• configured — leave blank to keep"
                : "Paste a SafeCertus ScimToken"
            }
            helperText={
              tenant?.hasIdpApiToken
                ? "A token is already configured. Leave blank to keep it, or paste a new one to replace it."
                : "Required to invite new tenant members by email. Mint a ScimToken for this tenant in SafeCertus's tenant console and paste it here."
            }
          />
        </Box>
      </DialogContent>

      <DialogActions>
        <Button onClick={onClose}>Cancel</Button>
        <Button
          variant="contained"
          onClick={handleSubmit}
          disabled={submitting || isDisabled}
        >
          Save Changes
        </Button>
      </DialogActions>
    </Dialog>
  );
}

function TenantMemberDialog({
  open,
  mode,
  member,
  submitting,
  onClose,
  onSubmit,
}) {
  const isEdit = mode === "edit";

  const [email, setEmail] = React.useState("");
  const [role, setRole] = React.useState("USER");
  const [isActive, setIsActive] = React.useState(true);

  React.useEffect(() => {
    if (open) {
      setEmail(member?.email || "");
      setRole(member?.role || "USER");
      setIsActive(Boolean(member?.isActive ?? true));
    } else {
      setEmail("");
      setRole("USER");
      setIsActive(true);
    }
  }, [open, member]);

  const handleSubmit = () => {
    if (isEdit) {
      onSubmit?.({
        subject: String(member?.subject || "").trim(),
        email: String(email || "").trim(),
        role,
        isActive,
      });
    } else {
      // Create mode invites by email — there's no `subject` (raw IDP user
      // id) yet. It's populated automatically once the invitee registers
      // and logs in for the first time, same as it is for every member
      // today (ensureTenantProvisioned on the backend).
      onSubmit?.({
        email: String(email || "").trim(),
        role,
      });
    }
  };

  const isDisabled = !String(email || "").trim();

  return (
    <Dialog open={open} onClose={onClose} fullWidth maxWidth="sm">
      <DialogTitle>
        {isEdit ? "Edit Tenant Member" : "Invite Tenant Member"}
      </DialogTitle>

      <DialogContent>
        <Box sx={{ display: "grid", gap: 2, pt: 1 }}>
          {!isEdit && (
            <Typography variant="body2" color="text.secondary">
              The recipient gets an email invite, registers in the IDP, and
              lands directly in this tenant on their first login.
            </Typography>
          )}

          {isEdit && (
            <TextField
              label="Subject"
              value={member?.subject || ""}
              fullWidth
              disabled
            />
          )}

          <TextField
            label="Email"
            value={email}
            onChange={(e) => setEmail(e.target.value)}
            fullWidth
            required
          />

          <TextField
            select
            label="Role"
            value={role}
            onChange={(e) => setRole(e.target.value)}
            fullWidth
          >
            <MenuItem value="OWNER">OWNER</MenuItem>
            <MenuItem value="ADMIN">ADMIN</MenuItem>
            <MenuItem value="USER">USER</MenuItem>
          </TextField>

          {isEdit && (
            <FormControlLabel
              control={
                <Switch
                  checked={isActive}
                  onChange={(e) => setIsActive(e.target.checked)}
                />
              }
              label={isActive ? "Active" : "Inactive"}
            />
          )}
        </Box>
      </DialogContent>

      <DialogActions>
        <Button onClick={onClose}>Cancel</Button>
        <Button
          variant="contained"
          onClick={handleSubmit}
          disabled={submitting || isDisabled}
        >
          {isEdit ? "Save Changes" : "Send Invite"}
        </Button>
      </DialogActions>
    </Dialog>
  );
}

function ConfirmDeleteDialog({
  open,
  title,
  description,
  submitting,
  error,
  onClose,
  onConfirm,
}) {
  return (
    <Dialog open={open} onClose={onClose} fullWidth maxWidth="xs">
      <DialogTitle>{title}</DialogTitle>

      <DialogContent>
        <Typography color="text.secondary">{description}</Typography>
        {error ? (
          <Alert
            severity="error"
            icon={<ReportProblemOutlinedIcon fontSize="small" sx={{ color: BRAND.alert.errorText }} />}
            sx={{
              mt: 2,
              bgcolor: BRAND.alert.errorSoft,
              color: BRAND.alert.errorText,
              border: `1px solid ${BRAND.alert.error}`,
              "& .MuiAlert-message": { color: BRAND.alert.errorText, fontWeight: 600 },
            }}
          >
            {error}
          </Alert>
        ) : null}
      </DialogContent>

      <DialogActions>
        <Button onClick={onClose}>Cancel</Button>
        <Button color="error" variant="contained" onClick={onConfirm} disabled={submitting}>
          Delete
        </Button>
      </DialogActions>
    </Dialog>
  );
}

export default function TenantsAdministrator({ mode = "global" }) {
  const theme = useTheme();
  const isMdDown = useMediaQuery(theme.breakpoints.down("md"));
  const isSmDown = useMediaQuery(theme.breakpoints.down("sm"));
  const { auth } = useAuthContext();

  const isTenantMode = mode === "tenant";
  const currentTenantId = auth?.tenantId;

  // Tenants list (global mode only): a parameterless on-mount fetch, routed
  // through useCachedFetch for stale-while-revalidate + dedup + last-known-good.
  // `tenants` is derived from the snapshot (setTenants was loader-only); the
  // selection reconciliation loadTenants used to do inline now lives in a
  // guarded effect below. In tenant mode the fetch is disabled.
  const {
    data: tenantsData,
    loading: loadingTenants,
    refetch: reloadTenants,
  } = useCachedFetch(
    "tenants:list:v1",
    async () => listFrom(await listTenants(), { keys: ["items"], context: "tenants.list" }),
    { enabled: !isTenantMode, staleMs: 30_000, storageMaxAgeMs: 5 * 60_000, revalidateOnMount: "stale" }
  );
  const tenants = React.useMemo(() => tenantsData ?? [], [tenantsData]);

  const [selectedTenant, setSelectedTenant] = React.useState(null);
  const [selectedTenantId, setSelectedTenantId] = React.useState(null);
  const [tenantDetails, setTenantDetails] = React.useState(null);
  const [members, setMembers] = React.useState([]);

  const [loadingMembers, setLoadingMembers] = React.useState(false);
  const [submitting, setSubmitting] = React.useState(false);

  const [tenantSearch, setTenantSearch] = React.useState("");
  const [memberSearch, setMemberSearch] = React.useState("");

  const [tenantDialogOpen, setTenantDialogOpen] = React.useState(false);
  const [memberDialogOpen, setMemberDialogOpen] = React.useState(false);
  const [memberDialogMode, setMemberDialogMode] = React.useState("create");

  const [deleteTenantOpen, setDeleteTenantOpen] = React.useState(false);
  const [deleteTenantError, setDeleteTenantError] = React.useState(null);
  const [deleteMemberOpen, setDeleteMemberOpen] = React.useState(false);
  const [deleteMemberError, setDeleteMemberError] = React.useState(null);

  const [editingTenant, setEditingTenant] = React.useState(null);
  const [editingMember, setEditingMember] = React.useState(null);

  const [membersFlash, setMembersFlash] = React.useState(false);

  const [snackbar, setSnackbar] = React.useState({
    open: false,
    message: "",
    severity: "success",
  });

  // Reconcile the selected tenant against the loaded list. Guarded on
  // `next !== selectedTenant` so it settles in one pass and can't loop:
  // - no selection yet → pick the first tenant
  // - existing selection → refresh it to the matching item (or clear if gone)
  // selectedTenant / selectedTenantId always move together (id follows object).
  React.useEffect(() => {
    if (isTenantMode || !tenantsData) return;
    const items = tenantsData;
    const next = !selectedTenant
      ? items[0] ?? null
      : items.find((t) => t.id === selectedTenant.id) ?? null;
    if (next !== selectedTenant) {
      setSelectedTenant(next);
      setSelectedTenantId(next?.id ?? null);
    }
  }, [tenantsData, isTenantMode, selectedTenant]);

  const loadTenantDetails = async (tenantId) => {
    if (!tenantId) {
      setTenantDetails(null);
      return;
    }

    try {
      const data = await getTenantById(tenantId);
      setTenantDetails(data ?? null);
    } catch (e) {
      console.error(e);
      setSnackbar({
        open: true,
        message: "Failed to load tenant details",
        severity: "error",
      });
      setTenantDetails(null);
    }
  };

  const loadMembers = async (tenantId) => {
    if (!tenantId) {
      setMembers([]);
      return;
    }

    try {
      setLoadingMembers(true);
      const response = await listTenantMembers(tenantId);
      setMembers(Array.isArray(response?.items) ? response.items : []);
      setMembersFlash(true);
    } catch (e) {
      console.error(e);
      setSnackbar({
        open: true,
        message: "Failed to load tenant members",
        severity: "error",
      });
    } finally {
      setLoadingMembers(false);
    }
  };


  React.useEffect(() => {
    if (isTenantMode) {
      if (currentTenantId) {
        loadTenantDetails(currentTenantId);
        loadMembers(currentTenantId);
      } else {
        setTenantDetails(null);
        setMembers([]);
      }
      return;
    }

    loadMembers(selectedTenant?.id);
  }, [isTenantMode, currentTenantId, selectedTenant?.id]);

  React.useEffect(() => {
    if (!membersFlash) return;

    const timer = setTimeout(() => {
      setMembersFlash(false);
    }, 900);

    return () => clearTimeout(timer);
  }, [membersFlash]);

  const filteredTenants = React.useMemo(() => {
    const q = tenantSearch.trim().toLowerCase();
    if (!q) return tenants;

    return tenants.filter((tenant) => {
      return (
        String(tenant?.name || "").toLowerCase().includes(q) ||
        String(tenant?.externalIdpTenant || "").toLowerCase().includes(q) ||
        String(tenant?.tenantDb || "").toLowerCase().includes(q)
      );
    });
  }, [tenants, tenantSearch]);

  const filteredMembers = React.useMemo(() => {
    const q = memberSearch.trim().toLowerCase();
    if (!q) return members;

    return members.filter((member) => {
      return (
        String(member?.subject || "").toLowerCase().includes(q) ||
        String(member?.email || "").toLowerCase().includes(q) ||
        String(member?.role || "").toLowerCase().includes(q)
      );
    });
  }, [members, memberSearch]);

  const summary = React.useMemo(() => {
    const totalTenants = tenants.length;
    const totalMembers = tenants.reduce(
      (acc, item) => acc + Number(item?.membersCount || 0),
      0
    );
    const activeMembers = tenants.reduce(
      (acc, item) => acc + Number(item?.activeMembersCount || 0),
      0
    );

    return { totalTenants, totalMembers, activeMembers };
  }, [tenants]);

  const openEditTenant = (tenant) => {
    setEditingTenant(tenant);
    setTenantDialogOpen(true);
  };

  const openEditMember = (member) => {
    setEditingMember(member);
    setMemberDialogMode("edit");
    setMemberDialogOpen(true);
  };

  const handleSubmitTenant = async (payload) => {
    if (!editingTenant?.id) return;

    try {
      setSubmitting(true);

      await updateTenant(editingTenant.id, payload);

      setSnackbar({
        open: true,
        message: "Tenant updated successfully",
        severity: "success",
      });

      setTenantDialogOpen(false);
      await reloadTenants();
    } catch (e) {
      console.error(e);
      setSnackbar({
        open: true,
        message: "Failed to save tenant",
        severity: "error",
      });
    } finally {
      setSubmitting(false);
    }
  };

  const handleDeleteTenant = async () => {
    if (!editingTenant?.id) return;

    try {
      setSubmitting(true);
      await deleteTenant(editingTenant.id);
      setDeleteTenantOpen(false);

      if (selectedTenant?.id === editingTenant.id) {
        setSelectedTenant(null);
        setSelectedTenantId(null);
        setMembers([]);
      }

      setSnackbar({
        open: true,
        message: "Tenant deleted successfully",
        severity: "success",
      });

      await reloadTenants();
    } catch (e) {
      console.error(e);
      const errorMessage = String(e?.message || "");
      const friendlyMessage = errorMessage.includes("TENANT_HAS_ACTIVE_MEMBERS")
        ? "Tenant has active members and cannot be deleted. Remove its members first."
        : "Failed to delete tenant";

      // Shown inline in the dialog (stays visible until the user acts) in
      // addition to the toast (which auto-hides after 4.5s and is easy to
      // miss while the confirm dialog is still open on top of it).
      setDeleteTenantError(friendlyMessage);
      setSnackbar({
        open: true,
        message: friendlyMessage,
        severity: "error",
      });
    } finally {
      setSubmitting(false);
    }
  };

  const handleSubmitMember = async (payload) => {
    const targetTenantId = isTenantMode ? currentTenantId : selectedTenant?.id;
    if (!targetTenantId) return;

    try {
      setSubmitting(true);

      if (memberDialogMode === "edit" && editingMember?.id) {
        await updateTenantMember(targetTenantId, editingMember.id, payload);
        setSnackbar({
          open: true,
          message: "Tenant member updated successfully",
          severity: "success",
        });
      } else {
        // No member row exists yet — it's auto-provisioned on the
        // invitee's first login. Say so, rather than implying a row
        // just got created.
        await createTenantMember(targetTenantId, payload);
        setSnackbar({
          open: true,
          message: `Invite sent to ${payload.email}`,
          severity: "success",
        });
      }

      setMemberDialogOpen(false);
      await loadMembers(targetTenantId);

      if (!isTenantMode) {
        await reloadTenants();
      }
    } catch (e) {
      console.error(e);

      let message = "Failed to save tenant member";
      if (e?.code === "IDP_TOKEN_NOT_CONFIGURED") {
        message =
          "This tenant has no IDP token configured yet. Open Edit Tenant and paste a SafeCertus ScimToken first.";
      } else if (e?.code === "IDP_INVITE_FAILED") {
        message = "The IDP rejected the invite. Check the tenant's IDP token and try again.";
      }

      setSnackbar({
        open: true,
        message,
        severity: "error",
      });
    } finally {
      setSubmitting(false);
    }
  };

  const handleDeleteMember = async () => {
    const targetTenantId = isTenantMode ? currentTenantId : selectedTenant?.id;
    if (!targetTenantId || !editingMember?.id) return;

    try {
      setSubmitting(true);
      await deleteTenantMember(targetTenantId, editingMember.id);
      setDeleteMemberOpen(false);

      setSnackbar({
        open: true,
        message: "Tenant member deleted successfully",
        severity: "success",
      });

      await loadMembers(targetTenantId);

      if (!isTenantMode) {
        await reloadTenants();
      }
    } catch (e) {
      console.error(e);
      const message = "Failed to delete tenant member";
      setDeleteMemberError(message);
      setSnackbar({
        open: true,
        message,
        severity: "error",
      });
    } finally {
      setSubmitting(false);
    }
  };

  const tenantColumns = [
    { field: "id", headerName: "ID", width: 70 },
    { field: "name", headerName: "Name", minWidth: 180, flex: 0.9 },
    {
      field: "externalIdpTenant",
      headerName: "External IdP Tenant",
      minWidth: 170,
      flex: 0.9,
    },
    { field: "tenantDb", headerName: "Tenant DB", minWidth: 170, flex: 0.9 },
    { field: "maxDevices", headerName: "Max Devices", minWidth: 120, flex: 0.6 },
    { field: "membersCount", headerName: "Members", minWidth: 100, flex: 0.5 },
    {
      field: "activeMembersCount",
      headerName: "Active Members",
      minWidth: 130,
      flex: 0.6,
    },
    {
      field: "createdAt",
      headerName: "Created At",
      minWidth: 160,
      flex: 0.8,
      renderCell: (params) => formatDate(params?.value),
    },
    {
      field: "actions",
      headerName: "Actions",
      minWidth: 180,
      flex: 0.9,
      sortable: false,
      filterable: false,
      renderCell: (params) => (
        <Box sx={{ display: "flex", gap: 1 }}>
          <Button size="small" onClick={() => openEditTenant(params.row)}>
            Edit
          </Button>
          <Button
            size="small"
            color="error"
            onClick={() => {
              setEditingTenant(params.row);
              setDeleteTenantError(null);
              setDeleteTenantOpen(true);
            }}
          >
            Delete
          </Button>
        </Box>
      ),
    },
  ];

  const memberColumns = [
    { field: "id", headerName: "ID", width: 70 },
    { field: "subject", headerName: "Subject", minWidth: 180, flex: 1 },
    { field: "email", headerName: "Email", minWidth: 220, flex: 1 },
    {
      field: "role",
      headerName: "Role",
      minWidth: 100,
      flex: 0.5,
      renderCell: (params) => renderRoleChip(params.value),
    },
    {
      field: "isActive",
      headerName: "Status",
      minWidth: 100,
      flex: 0.5,
      renderCell: (params) => renderActiveChip(params.value),
    },
    {
      field: "createdAt",
      headerName: "Created At",
      minWidth: 160,
      flex: 0.8,
      renderCell: (params) => formatDate(params?.value),
    },
    {
      field: "updatedAt",
      headerName: "Updated At",
      minWidth: 160,
      flex: 0.8,
      renderCell: (params) => formatDate(params?.value),
    },
    {
      field: "actions",
      headerName: "Actions",
      minWidth: 180,
      flex: 0.9,
      sortable: false,
      filterable: false,
      renderCell: (params) => (
        <Box sx={{ display: "flex", gap: 1 }}>
          <Button size="small" onClick={() => openEditMember(params.row)}>
            Edit
          </Button>
          <Button
            size="small"
            color="error"
            onClick={() => {
              setEditingMember(params.row);
              setDeleteMemberError(null);
              setDeleteMemberOpen(true);
            }}
          >
            Delete
          </Button>
        </Box>
      ),
    },
  ];

  const tenantColumnVisibilityModel = React.useMemo(() => {
    if (isSmDown) {
      return {
        externalIdpTenant: false,
        tenantDb: false,
        createdAt: false,
        activeMembersCount: false,
      };
    }

    if (isMdDown) {
      return {
        externalIdpTenant: false,
        createdAt: false,
      };
    }

    return {};
  }, [isMdDown, isSmDown]);

  const memberColumnVisibilityModel = React.useMemo(() => {
    if (isSmDown) {
      return {
        subject: false,
        createdAt: false,
        updatedAt: false,
      };
    }

    if (isMdDown) {
      return {
        updatedAt: false,
      };
    }

    return {};
  }, [isMdDown, isSmDown]);

  const displayedTenant = isTenantMode ? tenantDetails : selectedTenant;

  return (
    <Box sx={{ px: { xs: 2, sm: 0.5 }, py: { xs: 2, sm: 0.5 } }}>
      <PageHeader
        title={isTenantMode ? "Tenant Members" : "Tenant Administrator"}
        subtitle={
          isTenantMode
            ? "Manage members for your tenant"
            : "Manage tenants and tenant members"
        }
        icon={<BusinessOutlinedIcon />}
      />

      {!isTenantMode && (
        <>
          {/* Semantic KPIs — "Total Tenants" stays brand teal, the
              two member counts map to their natural roles: Members
              (neutral dark), Active (success green). */}
          <Box sx={{ mb: 2 }}>
            <Grid container spacing={2} alignItems="stretch">
              <Grid size={{ xs: 12, md: 2 }}>
                <SummaryCard title="Total Tenants" value={summary.totalTenants} />
              </Grid>

              <Grid size={{ xs: 12, md: 2 }}>
                <SummaryCard
                  title="Total Members"
                  value={summary.totalMembers}
                  accent={BRAND.dark}
                />
              </Grid>

              <Grid size={{ xs: 12, md: 2 }}>
                <SummaryCard
                  title="Active Members"
                  value={summary.activeMembers}
                  accent={BRAND.alert.success}
                />
              </Grid>
            </Grid>
          </Box>

          <SectionPaper
            variant="panel"
            sx={{
              p: { xs: 1.5, sm: 1.5 },
              mb: 2,
            }}
          >
            <Box
              sx={{
                display: "flex",
                justifyContent: "space-between",
                alignItems: { xs: "stretch", sm: "center" },
                gap: 2,
                mb: 1,
                flexWrap: "wrap",
                flexDirection: { xs: "column", sm: "row" },
              }}
            >
              <TextField
                label="Search tenants"
                size="small"
                value={tenantSearch}
                onChange={(e) => setTenantSearch(e.target.value)}
                sx={{ width: { xs: "100%", sm: 260 } }}
              />

              <Typography variant="body2" color="text.secondary">
                Click a tenant row to load its members
              </Typography>
            </Box>

            <Box
              sx={{
                height: {
                  xs: 420,
                  sm: "calc(100vh - 420px)",
                  md: 360,
                },
                width: "100%",
              }}
            >
              <DataGrid
                rows={filteredTenants}
                columns={tenantColumns}
                columnVisibilityModel={tenantColumnVisibilityModel}
                loading={loadingTenants}
                disableRowSelectionOnClick
                getRowId={(row) => row.id}
                pageSizeOptions={[10, 25, 50]}
                rowSelectionModel={{
                  type: "include",
                  ids:
                    selectedTenantId != null
                      ? new Set([selectedTenantId])
                      : new Set(),
                }}
                onRowClick={(params) => {
                  setSelectedTenant(params.row);
                  setSelectedTenantId(params.row.id);
                }}
                initialState={{
                  pagination: {
                    paginationModel: { pageSize: 10, page: 0 },
                  },
                }}
                sx={{
                  ...DATAGRID_SX,
                  width: "100%",
                }}
              />
            </Box>
          </SectionPaper>
        </>
      )}

      <SectionPaper
        variant="panel"
        sx={{ p: { xs: 1.5, sm: 1.5 } }}
      >
        <Box
          sx={{
            mb: 1.5,
            display: "flex",
            justifyContent: "space-between",
            alignItems: { xs: "stretch", sm: "center" },
            gap: 2,
            flexWrap: "wrap",
            flexDirection: { xs: "column", sm: "row" },
          }}
        >
          <Box>
            <Typography variant="h6" sx={{ fontWeight: 700 }}>
              Tenant Members
            </Typography>
            <Typography variant="body2" color="text.secondary">
              {isTenantMode
                ? "Manage members for your tenant"
                : displayedTenant
                  ? `Members for ${displayedTenant.name}`
                  : "Select a tenant to manage members"}
            </Typography>
          </Box>

          <Box sx={{ display: "flex", gap: 2, flexWrap: "wrap", width: { xs: "100%", sm: "auto" } }}>
            <TextField
              label="Search members"
              size="small"
              value={memberSearch}
              onChange={(e) => setMemberSearch(e.target.value)}
              sx={{ width: { xs: "100%", sm: 240 } }}
              disabled={!displayedTenant}
            />

            <Button
              variant="contained"
              onClick={() => {
                setEditingMember(null);
                setMemberDialogMode("create");
                setMemberDialogOpen(true);
              }}
              disabled={!displayedTenant}
            >
              Add Member
            </Button>
          </Box>
        </Box>

        {displayedTenant && (
          <>
            <Divider sx={{ mb: 1.5 }} />
            <Box sx={{ mb: 1.5 }}>
              <Typography variant="body2" color="text.secondary">
                <strong>Tenant DB:</strong> {displayedTenant.tenantDb} &nbsp;&nbsp;|&nbsp;&nbsp;
                <strong>External IdP Tenant:</strong> {displayedTenant.externalIdpTenant} &nbsp;&nbsp;|&nbsp;&nbsp;
                <strong>Max Devices:</strong> {displayedTenant.maxDevices}
              </Typography>
            </Box>
          </>
        )}

        <Box
          sx={{
            height: {
              xs: 420,
              sm: "calc(100vh - 430px)",
              md: 360,
            },
            width: "100%",
            borderRadius: 2,
            transition: "box-shadow 0.25s ease, background-color 0.25s ease",
            // Flash highlight when members refresh after a tenant click.
            // Now uses the brand teal instead of the old "#0f6b72" tone.
            boxShadow: membersFlash
              ? `0 0 0 2px ${BRAND.tealSoftStrong}, 0 0 18px ${BRAND.tealSoft}`
              : "none",
            backgroundColor: membersFlash ? BRAND.tealSoft : "transparent",
          }}
        >
          <DataGrid
            rows={filteredMembers}
            columns={memberColumns}
            columnVisibilityModel={memberColumnVisibilityModel}
            loading={loadingMembers}
            disableRowSelectionOnClick
            getRowId={(row) => row.id}
            pageSizeOptions={[10, 25, 50]}
            initialState={{
              pagination: {
                paginationModel: { pageSize: 10, page: 0 },
              },
            }}
            sx={{
              ...DATAGRID_SX,
              width: "100%",
            }}
          />
        </Box>
      </SectionPaper>

      <TenantDialog
        open={tenantDialogOpen}
        tenant={editingTenant}
        submitting={submitting}
        onClose={() => setTenantDialogOpen(false)}
        onSubmit={handleSubmitTenant}
      />

      <TenantMemberDialog
        open={memberDialogOpen}
        mode={memberDialogMode}
        member={editingMember}
        submitting={submitting}
        onClose={() => setMemberDialogOpen(false)}
        onSubmit={handleSubmitMember}
      />

      <ConfirmDeleteDialog
        open={deleteTenantOpen}
        title="Delete Tenant"
        description="This action will permanently delete the tenant record. If the tenant has active members, deletion may be blocked."
        submitting={submitting}
        error={deleteTenantError}
        onClose={() => {
          setDeleteTenantOpen(false);
          setDeleteTenantError(null);
        }}
        onConfirm={handleDeleteTenant}
      />

      <ConfirmDeleteDialog
        open={deleteMemberOpen}
        title="Delete Tenant Member"
        description="This action will permanently delete the tenant member."
        submitting={submitting}
        error={deleteMemberError}
        onClose={() => {
          setDeleteMemberOpen(false);
          setDeleteMemberError(null);
        }}
        onConfirm={handleDeleteMember}
      />

      <BrandSnackbar
        open={snackbar.open}
        severity={snackbar.severity}
        message={snackbar.message}
        onClose={() => setSnackbar((prev) => ({ ...prev, open: false }))}
      />
    </Box>
  );
}