import * as React from "react";
import Grid from "@mui/material/Grid";
import {
  Box,
  Paper,
  Typography,
  Button,
  TextField,
  MenuItem,
  Chip,
  Snackbar,
  Alert,
  Divider,
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  Switch,
  FormControlLabel,
  useMediaQuery,
  useTheme,
} from "@mui/material";
import { DataGrid } from "@mui/x-data-grid";

import {
  listTenants,
  createTenant,
  updateTenant,
  deleteTenant,
  listTenantMembers,
  createTenantMember,
  updateTenantMember,
  deleteTenantMember,
} from "../api/tenants";

function SummaryCard({ title, value, accent = "#1ba6a6" }) {
  return (
    <Paper
      sx={{
        p: 2,
        height: "75%",
        minHeight: 96,
        borderRadius: 3,
        border: "1px solid rgba(0,0,0,0.08)",
        boxShadow: "0 10px 24px rgba(0,0,0,0.08)",
        display: "flex",
        flexDirection: "column",
        justifyContent: "space-between",
      }}
    >
      <Typography sx={{ fontSize: 13, color: "text.secondary" }}>
        {title}
      </Typography>

      <Typography
        sx={{
          fontSize: 28,
          fontWeight: 800,
          color: accent,
          lineHeight: 1.1,
          mt: 1,
        }}
      >
        {value}
      </Typography>
    </Paper>
  );
}

function renderRoleChip(role) {
  const value = String(role || "").toUpperCase();

  if (value === "OWNER") {
    return <Chip label="OWNER" size="small" sx={{ fontWeight: 700 }} />;
  }

  if (value === "ADMIN") {
    return (
      <Chip
        label="ADMIN"
        size="small"
        sx={{
          bgcolor: "rgba(27,166,166,0.12)",
          color: "#0f6b72",
          fontWeight: 700,
        }}
      />
    );
  }

  if (value === "USER") {
    return (
      <Chip
        label="USER"
        size="small"
        sx={{
          bgcolor: "rgba(120,120,120,0.12)",
          color: "#555",
          fontWeight: 700,
        }}
      />
    );
  }

  return <Chip label={value || "UNKNOWN"} size="small" />;
}

function renderActiveChip(isActive) {
  return isActive ? (
    <Chip
      label="Active"
      size="small"
      sx={{
        bgcolor: "rgba(27,166,166,0.12)",
        color: "#0f6b72",
        fontWeight: 700,
      }}
    />
  ) : (
    <Chip
      label="Inactive"
      size="small"
      sx={{
        bgcolor: "rgba(211,47,47,0.12)",
        color: "#b3261e",
        fontWeight: 700,
      }}
    />
  );
}

function formatDate(value) {
  if (!value) return " - ";

  const date = new Date(value);

  return date.toLocaleString("en-US", {
    year: "2-digit",
    month: "short",
    day: "2-digit",
    hourCycle: "h24",
    hour: "2-digit",
    minute: "2-digit",
  });
}

function TenantDialog({
  open,
  mode,
  tenant,
  submitting,
  onClose,
  onSubmit,
}) {
  const [name, setName] = React.useState("");
  const [externalIdpTenant, setExternalIdpTenant] = React.useState("");
  const [maxDevices, setMaxDevices] = React.useState("");
  const [tenantDb, setTenantDb] = React.useState("");

  React.useEffect(() => {
    if (open) {
      setName(tenant?.name || "");
      setExternalIdpTenant(tenant?.externalIdpTenant || "");
      setMaxDevices(tenant?.maxDevices ?? "");
      setTenantDb(tenant?.tenantDb || "Auto-generated by backend");
    } else {
      setName("");
      setExternalIdpTenant("");
      setMaxDevices("");
      setTenantDb("");
    }
  }, [open, tenant]);

  const handleSubmit = () => {
    onSubmit?.({
      name: String(name || "").trim(),
      externalIdpTenant: String(externalIdpTenant || "").trim(),
      maxDevices: Number(maxDevices),
    });
  };

  const isDisabled =
    !String(name || "").trim() ||
    !String(externalIdpTenant || "").trim() ||
    String(maxDevices || "").trim() === "";

  return (
    <Dialog open={open} onClose={onClose} fullWidth maxWidth="sm">
      <DialogTitle>{mode === "edit" ? "Edit Tenant" : "Create Tenant"}</DialogTitle>

      <DialogContent>
        <Box sx={{ display: "grid", gap: 2, pt: 1 }}>
          <TextField
            label="Tenant Name"
            value={name}
            onChange={(e) => setName(e.target.value)}
            fullWidth
            required
          />

          <TextField
            label="Ext IdP Tenant"
            value={externalIdpTenant}
            onChange={(e) => setExternalIdpTenant(e.target.value)}
            fullWidth
            required
          />

          <TextField
            label="Tenant DB"
            value={tenantDb}
            fullWidth
            disabled
          />

          <TextField
            label="Max Devices"
            type="number"
            value={maxDevices}
            onChange={(e) => setMaxDevices(e.target.value)}
            fullWidth
            required
          />
        </Box>
      </DialogContent>

      <DialogActions>
        <Button onClick={onClose}>Cancel</Button>
        <Button
          variant="contained"
          onClick={handleSubmit}
          disabled={submitting || isDisabled}
        >
          {mode === "edit" ? "Save Changes" : "Create"}
        </Button>
      </DialogActions>
    </Dialog>
  );
}

function TenantMemberDialog({
  open,
  mode,
  member,
  submitting,
  onClose,
  onSubmit,
}) {
  const [subject, setSubject] = React.useState("");
  const [email, setEmail] = React.useState("");
  const [role, setRole] = React.useState("USER");
  const [isActive, setIsActive] = React.useState(true);

  React.useEffect(() => {
    if (open) {
      setSubject(member?.subject || "");
      setEmail(member?.email || "");
      setRole(member?.role || "USER");
      setIsActive(Boolean(member?.isActive ?? true));
    } else {
      setSubject("");
      setEmail("");
      setRole("USER");
      setIsActive(true);
    }
  }, [open, member]);

  const handleSubmit = () => {
    onSubmit?.({
      subject: String(subject || "").trim(),
      email: String(email || "").trim(),
      role,
      isActive,
    });
  };

  const isDisabled =
    !String(subject || "").trim() ||
    !String(email || "").trim();

  return (
    <Dialog open={open} onClose={onClose} fullWidth maxWidth="sm">
      <DialogTitle>
        {mode === "edit" ? "Edit Tenant Member" : "Add Tenant Member"}
      </DialogTitle>

      <DialogContent>
        <Box sx={{ display: "grid", gap: 2, pt: 1 }}>
          <TextField
            label="Subject"
            value={subject}
            onChange={(e) => setSubject(e.target.value)}
            fullWidth
            required
          />

          <TextField
            label="Email"
            value={email}
            onChange={(e) => setEmail(e.target.value)}
            fullWidth
            required
          />

          <TextField
            select
            label="Role"
            value={role}
            onChange={(e) => setRole(e.target.value)}
            fullWidth
          >
            <MenuItem value="OWNER">OWNER</MenuItem>
            <MenuItem value="ADMIN">ADMIN</MenuItem>
            <MenuItem value="USER">USER</MenuItem>
          </TextField>

          <FormControlLabel
            control={
              <Switch
                checked={isActive}
                onChange={(e) => setIsActive(e.target.checked)}
              />
            }
            label={isActive ? "Active" : "Inactive"}
          />
        </Box>
      </DialogContent>

      <DialogActions>
        <Button onClick={onClose}>Cancel</Button>
        <Button
          variant="contained"
          onClick={handleSubmit}
          disabled={submitting || isDisabled}
        >
          {mode === "edit" ? "Save Changes" : "Add Member"}
        </Button>
      </DialogActions>
    </Dialog>
  );
}

function ConfirmDeleteDialog({
  open,
  title,
  description,
  submitting,
  onClose,
  onConfirm,
}) {
  return (
    <Dialog open={open} onClose={onClose} fullWidth maxWidth="xs">
      <DialogTitle>{title}</DialogTitle>

      <DialogContent>
        <Typography color="text.secondary">{description}</Typography>
      </DialogContent>

      <DialogActions>
        <Button onClick={onClose}>Cancel</Button>
        <Button color="error" variant="contained" onClick={onConfirm} disabled={submitting}>
          Delete
        </Button>
      </DialogActions>
    </Dialog>
  );
}

export default function TenantsAdministrator() {
  const theme = useTheme();
  const isMdDown = useMediaQuery(theme.breakpoints.down("md"));
  const isSmDown = useMediaQuery(theme.breakpoints.down("sm"));

  const [tenants, setTenants] = React.useState([]);
  const [selectedTenant, setSelectedTenant] = React.useState(null);
  const [members, setMembers] = React.useState([]);

  const [loadingTenants, setLoadingTenants] = React.useState(true);
  const [loadingMembers, setLoadingMembers] = React.useState(false);
  const [submitting, setSubmitting] = React.useState(false);

  const [tenantSearch, setTenantSearch] = React.useState("");
  const [memberSearch, setMemberSearch] = React.useState("");

  const [tenantDialogOpen, setTenantDialogOpen] = React.useState(false);
  const [tenantDialogMode, setTenantDialogMode] = React.useState("create");

  const [memberDialogOpen, setMemberDialogOpen] = React.useState(false);
  const [memberDialogMode, setMemberDialogMode] = React.useState("create");

  const [deleteTenantOpen, setDeleteTenantOpen] = React.useState(false);
  const [deleteMemberOpen, setDeleteMemberOpen] = React.useState(false);

  const [editingTenant, setEditingTenant] = React.useState(null);
  const [editingMember, setEditingMember] = React.useState(null);

  const [selectedTenantId, setSelectedTenantId] = React.useState(null);
  const [membersFlash, setMembersFlash] = React.useState(false);

  const [snackbar, setSnackbar] = React.useState({
    open: false,
    message: "",
    severity: "success",
  });

  const loadTenants = async () => {
    try {
      setLoadingTenants(true);
      const response = await listTenants();
      const items = Array.isArray(response?.items) ? response.items : [];
      setTenants(items);

      if (!selectedTenant && items.length > 0) {
        setSelectedTenant(items[0]);
        setSelectedTenantId(items[0].id);
      } else if (selectedTenant) {
        const refreshed = items.find((t) => t.id === selectedTenant.id) || null;
        setSelectedTenant(refreshed);
        setSelectedTenantId(refreshed?.id ?? null);
      }
    } catch (e) {
      console.error(e);
      setSnackbar({
        open: true,
        message: "Failed to load tenants",
        severity: "error",
      });
    } finally {
      setLoadingTenants(false);
    }
  };

  const loadMembers = async (tenantId) => {
    if (!tenantId) {
      setMembers([]);
      return;
    }

    try {
      setLoadingMembers(true);
      const response = await listTenantMembers(tenantId);
      setMembers(Array.isArray(response?.items) ? response.items : []);
      setMembersFlash(true);
    } catch (e) {
      console.error(e);
      setSnackbar({
        open: true,
        message: "Failed to load tenant members",
        severity: "error",
      });
    } finally {
      setLoadingMembers(false);
    }
  };

  React.useEffect(() => {
    loadTenants();
  }, []);

  React.useEffect(() => {
    loadMembers(selectedTenant?.id);
  }, [selectedTenant?.id]);

  React.useEffect(() => {
    if (!membersFlash) return;

    const timer = setTimeout(() => {
      setMembersFlash(false);
    }, 900);

    return () => clearTimeout(timer);
  }, [membersFlash]);

  const filteredTenants = React.useMemo(() => {
    const q = tenantSearch.trim().toLowerCase();
    if (!q) return tenants;

    return tenants.filter((tenant) => {
      return (
        String(tenant?.name || "").toLowerCase().includes(q) ||
        String(tenant?.externalIdpTenant || "").toLowerCase().includes(q) ||
        String(tenant?.tenantDb || "").toLowerCase().includes(q)
      );
    });
  }, [tenants, tenantSearch]);

  const filteredMembers = React.useMemo(() => {
    const q = memberSearch.trim().toLowerCase();
    if (!q) return members;

    return members.filter((member) => {
      return (
        String(member?.subject || "").toLowerCase().includes(q) ||
        String(member?.email || "").toLowerCase().includes(q) ||
        String(member?.role || "").toLowerCase().includes(q)
      );
    });
  }, [members, memberSearch]);

  const summary = React.useMemo(() => {
    const totalTenants = tenants.length;
    const totalMembers = tenants.reduce(
      (acc, item) => acc + Number(item?.membersCount || 0),
      0
    );
    const activeMembers = tenants.reduce(
      (acc, item) => acc + Number(item?.activeMembersCount || 0),
      0
    );

    return { totalTenants, totalMembers, activeMembers };
  }, [tenants]);

  const openCreateTenant = () => {
    setEditingTenant(null);
    setTenantDialogMode("create");
    setTenantDialogOpen(true);
  };

  const openEditTenant = (tenant) => {
    setEditingTenant(tenant);
    setTenantDialogMode("edit");
    setTenantDialogOpen(true);
  };

  const openCreateMember = () => {
    setEditingMember(null);
    setMemberDialogMode("create");
    setMemberDialogOpen(true);
  };

  const openEditMember = (member) => {
    setEditingMember(member);
    setMemberDialogMode("edit");
    setMemberDialogOpen(true);
  };

  const handleSubmitTenant = async (payload) => {
    try {
      setSubmitting(true);

      if (tenantDialogMode === "edit" && editingTenant?.id) {
        await updateTenant(editingTenant.id, payload);
        setSnackbar({
          open: true,
          message: "Tenant updated successfully",
          severity: "success",
        });
      } else {
        await createTenant(payload);
        setSnackbar({
          open: true,
          message: "Tenant created successfully",
          severity: "success",
        });
      }

      setTenantDialogOpen(false);
      await loadTenants();
    } catch (e) {
      console.error(e);
      setSnackbar({
        open: true,
        message: "Failed to save tenant",
        severity: "error",
      });
    } finally {
      setSubmitting(false);
    }
  };

  const handleDeleteTenant = async () => {
    if (!editingTenant?.id) return;

    try {
      setSubmitting(true);
      await deleteTenant(editingTenant.id);
      setDeleteTenantOpen(false);

      if (selectedTenant?.id === editingTenant.id) {
        setSelectedTenant(null);
        setMembers([]);
      }

      setSnackbar({
        open: true,
        message: "Tenant deleted successfully",
        severity: "success",
      });

      await loadTenants();
    } catch (e) {
        console.error(e);
        const errorMessage = String(e?.message || "");

        setSnackbar({
        open: true,
        message: errorMessage.includes("TENANT_HAS_ACTIVE_MEMBERS")
            ? "Tenant has active members and cannot be deleted"
            : "Failed to delete tenant",
        severity: "error",
        });
    } finally {
      setSubmitting(false);
    }
  };

  const handleSubmitMember = async (payload) => {
    if (!selectedTenant?.id) return;

    try {
      setSubmitting(true);

      if (memberDialogMode === "edit" && editingMember?.id) {
        await updateTenantMember(selectedTenant.id, editingMember.id, payload);
        setSnackbar({
          open: true,
          message: "Tenant member updated successfully",
          severity: "success",
        });
      } else {
        await createTenantMember(selectedTenant.id, payload);
        setSnackbar({
          open: true,
          message: "Tenant member created successfully",
          severity: "success",
        });
      }

      setMemberDialogOpen(false);
      await loadMembers(selectedTenant.id);
      await loadTenants();
    } catch (e) {
      console.error(e);
      setSnackbar({
        open: true,
        message: "Failed to save tenant member",
        severity: "error",
      });
    } finally {
      setSubmitting(false);
    }
  };

  const handleDeleteMember = async () => {
    if (!selectedTenant?.id || !editingMember?.id) return;

    try {
      setSubmitting(true);
      await deleteTenantMember(selectedTenant.id, editingMember.id);
      setDeleteMemberOpen(false);

      setSnackbar({
        open: true,
        message: "Tenant member deleted successfully",
        severity: "success",
      });

      await loadMembers(selectedTenant.id);
      await loadTenants();
    } catch (e) {
      console.error(e);
      setSnackbar({
        open: true,
        message: "Failed to delete tenant member",
        severity: "error",
      });
    } finally {
      setSubmitting(false);
    }
  };

  const tenantColumns = [
    { field: "id", headerName: "ID", width: 70 },
    { field: "name", headerName: "Name", minWidth: 180, flex: 0.9 },
    {
      field: "externalIdpTenant",
      headerName: "External IdP Tenant",
      minWidth: 170,
      flex: 0.9,
    },
    { field: "tenantDb", headerName: "Tenant DB", minWidth: 170, flex: 0.9 },
    { field: "maxDevices", headerName: "Max Devices", minWidth: 120, flex: 0.6 },
    { field: "membersCount", headerName: "Members", minWidth: 100, flex: 0.5 },
    {
      field: "activeMembersCount",
      headerName: "Active Members",
      minWidth: 130,
      flex: 0.6,
    },
    {
      field: "createdAt",
      headerName: "Created At",
      minWidth: 160,
      flex: 0.8,
      renderCell: (params) => formatDate(params?.value),
    },
    {
      field: "actions",
      headerName: "Actions",
      minWidth: 180,
      flex: 0.9,
      sortable: false,
      filterable: false,
      renderCell: (params) => (
        <Box sx={{ display: "flex", gap: 1 }}>
          <Button size="small" onClick={() => openEditTenant(params.row)}>
            Edit
          </Button>
          <Button
            size="small"
            color="error"
            onClick={() => {
              setEditingTenant(params.row);
              setDeleteTenantOpen(true);
            }}
          >
            Delete
          </Button>
        </Box>
      ),
    },
  ];

  const memberColumns = [
    { field: "id", headerName: "ID", width: 70 },
    { field: "subject", headerName: "Subject", minWidth: 180, flex: 1 },
    { field: "email", headerName: "Email", minWidth: 220, flex: 1 },
    {
      field: "role",
      headerName: "Role",
      minWidth: 100,
      flex: 0.5,
      renderCell: (params) => renderRoleChip(params.value),
    },
    {
      field: "isActive",
      headerName: "Status",
      minWidth: 100,
      flex: 0.5,
      renderCell: (params) => renderActiveChip(params.value),
    },
    {
      field: "createdAt",
      headerName: "Created At",
      minWidth: 160,
      flex: 0.8,
      renderCell: (params) => formatDate(params?.value),
    },
    {
      field: "updatedAt",
      headerName: "Updated At",
      minWidth: 160,
      flex: 0.8,
      renderCell: (params) => formatDate(params?.value),
    },
    {
      field: "actions",
      headerName: "Actions",
      minWidth: 180,
      flex: 0.9,
      sortable: false,
      filterable: false,
      renderCell: (params) => (
        <Box sx={{ display: "flex", gap: 1 }}>
          <Button size="small" onClick={() => openEditMember(params.row)}>
            Edit
          </Button>
          <Button
            size="small"
            color="error"
            onClick={() => {
              setEditingMember(params.row);
              setDeleteMemberOpen(true);
            }}
          >
            Delete
          </Button>
        </Box>
      ),
    },
  ];

  const tenantColumnVisibilityModel = React.useMemo(() => {
    if (isSmDown) {
      return {
        externalIdpTenant: false,
        tenantDb: false,
        createdAt: false,
        activeMembersCount: false,
      };
    }

    if (isMdDown) {
      return {
        externalIdpTenant: false,
        createdAt: false,
      };
    }

    return {};
  }, [isMdDown, isSmDown]);

  const memberColumnVisibilityModel = React.useMemo(() => {
    if (isSmDown) {
      return {
        subject: false,
        createdAt: false,
        updatedAt: false,
      };
    }

    if (isMdDown) {
      return {
        updatedAt: false,
      };
    }

    return {};
  }, [isMdDown, isSmDown]);

  return (
    <Box sx={{ px: { xs: 2, sm: 0.5 }, py: { xs: 2, sm: 0.5 } }}>
      <Box
        sx={{
          mb: 0.5,
          display: "inline-flex",
          justifyContent: "space-between",
          alignItems: { xs: "stretch", sm: "center" },
          gap: 2,
          flexWrap: "wrap",
          flexDirection: { xs: "column", sm: "row" },
        }}
      >
        <Box>
          <Typography variant="h4" color="#1ba6a6" sx={{ fontWeight: 700 }}>
            Tenant Administrator
          </Typography>
          <Typography variant="body1" color="text.secondary">
            Manage tenants and tenant members
          </Typography>
        </Box>

        <Button
          variant="contained"
          onClick={openCreateTenant}
          fullWidth={isSmDown}
          sx={{
            bgcolor: "#1ba6a6",
            "&:hover": { bgcolor: "#158d8d" },
            minWidth: { xs: "100%", sm: 170 },
            alignSelf: { xs: "stretch", sm: "center" },
          }}
        >
          + CREATE TENANT
        </Button>
      </Box>

      <Box sx={{ mb: 2 }}>
        <Grid container spacing={2} alignItems="stretch">
          <Grid size={{ xs: 12, md: 2 }}>
            <SummaryCard title="Total Tenants" value={summary.totalTenants} />
          </Grid>

          <Grid size={{ xs: 12, md: 2 }}>
            <SummaryCard
              title="Total Members"
              value={summary.totalMembers}
              accent="#0f6b72"
            />
          </Grid>

          <Grid size={{ xs: 12, md: 2 }}>
            <SummaryCard
              title="Active Members"
              value={summary.activeMembers}
              accent="#b3261e"
            />
          </Grid>
        </Grid>
      </Box>

      <Paper
        elevation={0}
        sx={{
          p: { xs: 1.5, sm: 1.5 },
          borderRadius: 3,
          border: "1px solid rgba(0,0,0,0.08)",
          boxShadow: "0 10px 24px rgba(0,0,0,0.06)",
          mb: 2,
        }}
      >
        <Box
          sx={{
            display: "flex",
            justifyContent: "space-between",
            alignItems: { xs: "stretch", sm: "center" },
            gap: 2,
            mb: 1,
            flexWrap: "wrap",
            flexDirection: { xs: "column", sm: "row" },
          }}
        >
          <TextField
            label="Search tenants"
            size="small"
            value={tenantSearch}
            onChange={(e) => setTenantSearch(e.target.value)}
            sx={{ width: { xs: "100%", sm: 260 } }}
          />

          <Typography variant="body2" color="text.secondary">
            Click a tenant row to load its members
          </Typography>
        </Box>

        <Box
          sx={{
            height: {
              xs: 420,
              sm: "calc(100vh - 420px)",
              md: 360,
            },
            width: "100%",
          }}
        >
          <DataGrid
            rows={filteredTenants}
            columns={tenantColumns}
            columnVisibilityModel={tenantColumnVisibilityModel}
            loading={loadingTenants}
            disableRowSelectionOnClick
            getRowId={(row) => row.id}
            pageSizeOptions={[10, 25, 50]}
            rowSelectionModel={{
                type: "include",
                ids: selectedTenantId != null ? new Set([selectedTenantId]) : new Set(),
            }}
            onRowClick={(params) => {
              setSelectedTenant(params.row);
              setSelectedTenantId(params.row.id);
            }}
            initialState={{
              pagination: {
                paginationModel: { pageSize: 10, page: 0 },
              },
            }}
            sx={{
              border: "none",
              width: "100%",
              "& .MuiDataGrid-columnHeaders": {
                backgroundColor: "rgba(166, 83, 27, 0.08)",
                fontWeight: 700,
              },
              "& .MuiDataGrid-row": {
                cursor: "pointer",
              },
              "& .MuiDataGrid-row.Mui-selected": {
                backgroundColor: "rgba(15, 107, 114, 0.18) !important",
              },
              "& .MuiDataGrid-row.Mui-selected:hover": {
                backgroundColor: "rgba(15, 107, 114, 0.24) !important",
              },
            }}
          />
        </Box>
      </Paper>

      <Paper
        elevation={0}
        sx={{
          p: { xs: 1.5, sm: 1.5 },
          borderRadius: 3,
          border: "1px solid rgba(0,0,0,0.08)",
          boxShadow: "0 10px 24px rgba(0,0,0,0.06)",
        }}
      >
        <Box
          sx={{
            mb: 1.5,
            display: "flex",
            justifyContent: "space-between",
            alignItems: { xs: "stretch", sm: "center" },
            gap: 2,
            flexWrap: "wrap",
            flexDirection: { xs: "column", sm: "row" },
          }}
        >
          <Box>
            <Typography variant="h6" sx={{ fontWeight: 700 }}>
              Tenant Members
            </Typography>
            <Typography variant="body2" color="text.secondary">
              {selectedTenant
                ? `Members for ${selectedTenant.name}`
                : "Select a tenant to manage members"}
            </Typography>
          </Box>

          <Box sx={{ display: "flex", gap: 2, flexWrap: "wrap", width: { xs: "100%", sm: "auto" } }}>
            <TextField
              label="Search members"
              size="small"
              value={memberSearch}
              onChange={(e) => setMemberSearch(e.target.value)}
              sx={{ width: { xs: "100%", sm: 240 } }}
              disabled={!selectedTenant}
            />

            <Button
              variant="contained"
              onClick={openCreateMember}
              disabled={!selectedTenant}
              sx={{
                bgcolor: "#1ba6a6",
                "&:hover": { bgcolor: "#158d8d" },
                width: { xs: "100%", sm: "auto" },
              }}
            >
              + ADD MEMBER
            </Button>
          </Box>
        </Box>

        {selectedTenant && (
          <>
            <Divider sx={{ mb: 1.5 }} />
            <Box sx={{ mb: 1.5 }}>
              <Typography variant="body2" color="text.secondary">
                <strong>Tenant DB:</strong> {selectedTenant.tenantDb} &nbsp;&nbsp;|&nbsp;&nbsp;
                <strong>External IdP Tenant:</strong> {selectedTenant.externalIdpTenant} &nbsp;&nbsp;|&nbsp;&nbsp;
                <strong>Max Devices:</strong> {selectedTenant.maxDevices}
              </Typography>
            </Box>
          </>
        )}

        <Box
          sx={{
            height: {
              xs: 420,
              sm: "calc(100vh - 430px)",
              md: 360,
            },
            width: "100%",
            borderRadius: 2,
            transition: "box-shadow 0.25s ease, background-color 0.25s ease",
            boxShadow: membersFlash
              ? "0 0 0 2px rgba(15, 107, 114, 0.25), 0 0 18px rgba(15, 107, 114, 0.12)"
              : "none",
            backgroundColor: membersFlash
              ? "rgba(15, 107, 114, 0.04)"
              : "transparent",
          }}
        >
          <DataGrid
            rows={filteredMembers}
            columns={memberColumns}
            columnVisibilityModel={memberColumnVisibilityModel}
            loading={loadingMembers}
            disableRowSelectionOnClick
            getRowId={(row) => row.id}
            pageSizeOptions={[10, 25, 50]}
            initialState={{
              pagination: {
                paginationModel: { pageSize: 10, page: 0 },
              },
            }}
            sx={{
              border: "none",
              width: "100%",
              "& .MuiDataGrid-columnHeaders": {
                backgroundColor: "rgba(166, 83, 27, 0.08)",
                fontWeight: 700,
              },
            }}
          />
        </Box>
      </Paper>

      <TenantDialog
        open={tenantDialogOpen}
        mode={tenantDialogMode}
        tenant={editingTenant}
        submitting={submitting}
        onClose={() => setTenantDialogOpen(false)}
        onSubmit={handleSubmitTenant}
      />

      <TenantMemberDialog
        open={memberDialogOpen}
        mode={memberDialogMode}
        member={editingMember}
        submitting={submitting}
        onClose={() => setMemberDialogOpen(false)}
        onSubmit={handleSubmitMember}
      />

      <ConfirmDeleteDialog
        open={deleteTenantOpen}
        title="Delete Tenant"
        description="This action will permanently delete the tenant record. If the tenant has active members, deletion may be blocked."
        submitting={submitting}
        onClose={() => setDeleteTenantOpen(false)}
        onConfirm={handleDeleteTenant}
      />

      <ConfirmDeleteDialog
        open={deleteMemberOpen}
        title="Delete Tenant Member"
        description="This action will permanently delete the tenant member."
        submitting={submitting}
        onClose={() => setDeleteMemberOpen(false)}
        onConfirm={handleDeleteMember}
      />

      <Snackbar
        open={snackbar.open}
        autoHideDuration={3500}
        onClose={() => setSnackbar((prev) => ({ ...prev, open: false }))}
        anchorOrigin={{ vertical: "bottom", horizontal: "right" }}
      >
        <Alert
          severity={snackbar.severity}
          onClose={() => setSnackbar((prev) => ({ ...prev, open: false }))}
          variant="filled"
        >
          {snackbar.message}
        </Alert>
      </Snackbar>
    </Box>
  );
}